"""schema inicial users con role + categorias + productos + movimientos

Revision ID: 61f4a2d08889
Revises: 
Create Date: 2026-05-05 00:23:50.595785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f4a2d08889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='operador', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin','operador')", name='users_role_check'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stock_actual', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stock_min', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('precio >= 0', name='productos_precio_no_negativo'),
    sa.CheckConstraint('stock_actual >= 0', name='productos_stock_no_negativo'),
    sa.CheckConstraint('stock_min >= 0', name='productos_stock_min_no_negativo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_sku'), ['sku'], unique=True)

    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_resultante', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo IN ('entrada','salida','ajuste')", name='movimientos_tipo_check'),
    sa.CheckConstraint('cantidad > 0', name='movimientos_cantidad_positiva'),
    sa.CheckConstraint('stock_anterior >= 0', name='movimientos_stock_anterior_no_neg'),
    sa.CheckConstraint('stock_resultante >= 0', name='movimientos_stock_resultante_no_neg'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_producto_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_fecha'))

    op.drop_table('movimientos')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_sku'))
        batch_op.drop_index(batch_op.f('ix_productos_categoria_id'))

    op.drop_table('productos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
