"""precio_unitario precio_pack_caja en productos tipo_unidad en venta_items

Revision ID: 7885f8d7af86
Revises: e8555f94fc72
Create Date: 2026-05-05 16:07:15.311383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7885f8d7af86'
down_revision = 'e8555f94fc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('precio_pack_caja', sa.Integer(), nullable=True))
        batch_op.drop_column('precio')

    with op.batch_alter_table('venta_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_unidad', sa.String(length=16), server_default='unidad', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_items', schema=None) as batch_op:
        batch_op.drop_column('tipo_unidad')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.drop_column('precio_pack_caja')
        batch_op.drop_column('precio_unitario')

    # ### end Alembic commands ###
