"""agregar tipos_precio eliminar precio_unitario precio_pack_caja tipo_unidad

Revision ID: a2146e371637
Revises: 7885f8d7af86
Create Date: 2026-05-05 16:25:30.861145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2146e371637'
down_revision = '7885f8d7af86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.CheckConstraint('precio >= 0', name='tipos_precio_precio_no_negativo'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'nombre', name='tipos_precio_producto_nombre_uq')
    )
    with op.batch_alter_table('tipos_precio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_precio_producto_id'), ['producto_id'], unique=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('precio_pack_caja')
        batch_op.drop_column('precio_unitario')

    with op.batch_alter_table('venta_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_precio_nombre', sa.String(length=60), server_default='Unidad', nullable=False))
        batch_op.drop_column('tipo_unidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_unidad', sa.VARCHAR(length=16), server_default=sa.text("'unidad'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('tipo_precio_nombre')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio_pack_caja', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('tipos_precio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_precio_producto_id'))

    op.drop_table('tipos_precio')
    # ### end Alembic commands ###
