"""add unidades to tipos_precio

Revision ID: b94de9bad7fc
Revises: 9ca8e3d63484
Create Date: 2026-05-05 20:35:00.685985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94de9bad7fc'
down_revision = '9ca8e3d63484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_precio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidades', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_precio', schema=None) as batch_op:
        batch_op.drop_column('unidades')

    # ### end Alembic commands ###
