"""agregar tablas ventas y venta_items

Revision ID: e8555f94fc72
Revises: 61f4a2d08889
Create Date: 2026-05-05 15:10:42.364123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8555f94fc72'
down_revision = '61f4a2d08889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.CheckConstraint('total >= 0', name='ventas_total_no_negativo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('venta_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='venta_items_cantidad_positiva'),
    sa.CheckConstraint('precio_unitario >= 0', name='venta_items_precio_no_negativo'),
    sa.CheckConstraint('subtotal >= 0', name='venta_items_subtotal_no_negativo'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_items_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_items_venta_id'), ['venta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_items_venta_id'))
        batch_op.drop_index(batch_op.f('ix_venta_items_producto_id'))

    op.drop_table('venta_items')
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_ventas_fecha'))

    op.drop_table('ventas')
    # ### end Alembic commands ###
